default: &default
  host: localhost
  username: postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_store-dip_development

test:
  <<: *default
  database: book_store-dip_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['BOOK_STORE_DATABASE_PASSWORD'] %>
